
rss: /atom.xml

# Pagination
## Set per_page to 0 to disable pagination
per_page: 4
pagination_dir: page

# Content
#excerpt_link: Read More
#fancybox: true

# Sidebar
#sidebar: right
#widgets:
#- category
#- tag
#- tagcloud
#- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# Miscellaneous
#google_analytics:
#favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


category_generator:
  per_page: 40

archive_generator:
  per_page: 40
  yearly: true
  monthly: false
  daily: false