
avatar: "http://7xrlc3.com1.z0.glb.clouddn.com/IMG_2025-min.JPG"

since: 2015

quote: "My mind is my weapon...And a mind needs books as a sword needs a whetstone, if it is to keep its edge. "

favicon: /favicon.ico