<!DOCTYPE html>
<html lang="en">
<head>
    {% include '_partial/head.swig' %}
</head>
<body class="night">
<div class="container">
    <div class="sidebar"></div>
    <div class="main-container">
        <div class="aside"></div>
        <div class="main-wrapper">
        {% include '_partial/tabnav.swig' %}
            <div class="tab-content">

            </div>
        </div>
    </div>
</div>
</body>
</html>