<div class="header">
    <a class="btn" href="/"><img class="avatar" src="{{ theme.avatar }}" alt=""></a>
    <div class="right-btn-group">
        <a class="btn" href="/"><i class="iconfont icon-home"></i></a>
        <a class="scroll btn" href="#my-ds-comments"><i class="iconfont icon-comment"></i></a>
        <a class="btn" href=""><i class="iconfont icon-collapsedown on"></i></a>
    </div>

</div>